swagger: "2.0"
info:
  version: 1.0.0
  title: JeCompare API
  license:
    name: MIT
host: api.dvoyd.com
basePath: /v1
schemes:
  - http
  - https
consumes:
  - application/json
  - application/xml
produces:
  - application/json
  - application/xml
paths:
  /products:
    get:
      summary: List all products
      operationId: ListProduct
      produces :
        - application/json
        - application/xml
      tags:
        - products
      parameters:
        - in      : query 
          name    : limit
          description : How many items to return at one time (max 100)
          required    : false
          type        : integer
      responses:
        "200":
          description: An paged array of products
          schema : 
            type: array
            $ref : '#/definitions/Product'
          headers:
            x-next:
              type: string
              description: A link to the next page of responses
          schema:
            $ref: '#/definitions/Products'
        "400"  :
          description : The specified query is invalid 
        "404" :
          description : Content not found
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      summary: Create a Products
      operationId: CreateProduct
      tags:
        - Products
      consumes :
        - application/json
      parameters :
        - in   : body 
          name : product 
          schema :
            $ref : '#/definitions/Product'
      description : "Permet de sauvegarder des informations"
      responses:
        "201":
          description: Product created 
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /products/{query}:
    get:
      summary: Info for a specific query
      operationId: showQueryResult
      tags:
        - products
      produces :
        - application/json
        - application/xml

      parameters:
        - name  : query
          in    : path
          required : true
          description : The query of the products to retrieve
          type   : string
      responses:
        "200":
          description: Expected response to a valid request
          schema:
            $ref: '#/definitions/Products'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Product:
    required:
      - name
      - categories
      - name_index
      - price
      - price_index
      - image
      - description
      - links
      - link 
      - domaine
      - crawled
      - service
      - tag 
    properties:
      name:
        type: string
      name_index :
        type : string
      categories :
        type : string
      price  :
        type : integer
      price_index : 
        type : string
      image : 
        type : string
      description :
        type : string
      links : 
        type : object
      link :
        type : string
      domaine : 
        type : string
      crawled :
        type : string
        format : date
      service :
        type : boolean
      tag:
        type: string
  Products:
    type: array
    items:
      $ref: '#/definitions/Product'
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
